name: MCMMRequester
version: '0.1.0'
main: io.lcmonitor.mcmmrequester.MCMMRequesterPlugin
api-version: '1.16'
authors: [LCMonitor]
commands:
  mcmm:
    description: MCMM command entrypoint
    usage: "/mcmm world request/create/list/set/info/remove ... | /mcmm template list | /mcmm instance list | /mcmm confirm | /mcmm help"
    permission: mcmmrequester.use
permissions:
  mcmmrequester.use:
    description: Allows player to use /mcmm commands
    default: true
